# Site settings
title: Rohit Deshpande
email: singlebinary@gmail.com
author: Rohit Deshpande
description: ""
baseurl: ""
url: "/"
google_analytics:
animated: true
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
sass:
  compressed: true

  name: Rohit
  email: singlebinary@gmail.com
  github: singlebinary
  twitter: singlebinary
  linkedin: www.linkedin.com/in/rohitsdeshpande/
  bio: Rohit Deshpande <br>
       Data Scientist & Astronomer
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
comments: true